### ISSUE TITLE
Step 6 setting up server missed a step or explanation

### ISSUE THREAD

**Issue by Sami-117** [googlecodelabs/android-network-security-config#10]
In Step 6 it asks us to set up a server. but the very first command prompt doesn't work if you don't have something like nodejs installed. it will only give an error saying "npm is not recognised"

**Comment by nic0lette** [comment]
Hi @samiwar 

That's true, but in the "Introduction" section it says:

> # What you'll need
> * The latest version of Android Studio
> * An Android device or emulator running at least Android 7.0 (API level 24 or higher)
> * **Node.js (or access to a configurable web server)**

That said, thank you for raising this issue. I'll update the text around there to provide more details.
