### ISSUE TITLE
Certificate generation without extensions

### ISSUE THREAD

**Issue by zanyx** [googlecodelabs/android-network-security-config#4]
Using the supplied command to create the debug certificate causes the app to receive the following error:
```
javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:
       certificate: sha1/xPOGU6cVKsoJj0fEGu9lCgoSZU8=
       DN: CN=localhost,O=Debug Cert,C=US
        subjectAltNames: []
javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:
        certificate: sha1/xPOGU6cVKsoJj0fEGu9lCgoSZU8=
        DN: CN=localhost,O=Debug Cert,C=US
        subjectAltNames: []
```

This is probably caused by a missing configuration of the v3 extension section.

I've found a possible solution to the issue using the following command to generate the certificate:
```
openssl req -x509 -new -nodes -days 100 -key root-ca-privkey.pem -out root-ca.cert.pem -subj "/C=US/O=Debug certificate/CN=localhost" -extensions v3_ca -config openssl_config.txt
```
You can find the file **openssl_config.txt** [here](https://github.com/googlecodelabs/android-network-security-config/files/2281115/openssl_config.txt).
I hope this helps.

**Comment by rafaelsm** [comment]
Someone update the codelab instructions please.

**Comment by nic0lette** [comment]
Thank you for the report and input. Text has been updated.
