### ISSUE TITLE
Confused enabled vs disabled

### ISSUE THREAD

**Issue by wusadurski** [googlecodelabs/android-network-security-config#6]
"Maintaining a whitelist of domains for which cleartext traffic should NOT be allowed is not recommended. You should disable cleartext traffic for all domains and only disable it for specific domains if your configuration requires it."

I guess the second sentence here should be "You should disable cleartext traffic for all domains and only **enable** it for specific domains if your configuration requires it"

**Comment by begomez** [comment]
Whitelist text mentioned before is still not updated.

**Comment by nic0lette** [comment]
Thank you for the report, and sorry for the delays. Text has been updated.
