### ISSUE TITLE
Missing debug-override code sample

### ISSUE THREAD

**Issue by Antimonit** [googlecodelabs/android-network-security-config#9]
In step **7. Debug overrides** is discussed how `debug-override` can be used to safely override config only for debug version of the app:

> Instead of adding a blanket whitelist for this use case or modifying the code, the `debug-override` option in the Network Security Configuration allows you to set security options that only apply when the application is run in debug mode; that is, when `android:debuggable` is true.

> Next, we will use a `debug-override` option in the network security configuration to whitelist this custom certificate authority only for the `localhost` domain:

But it is not actually used in any of the code samples.

**Comment by nic0lette** [comment]
Thank you for the input. I've updated the steps to include this in step 7 and it should be available shortly.
